

const aceThemes = {
}

aceThemes['Ambiance'] = require('ace-builds/src-noconflict/theme-ambiance')
aceThemes['GitHub Dark'] = require('ace-builds/src-noconflict/theme-github_dark')
aceThemes['Nord Dark'] = require('ace-builds/src-noconflict/theme-nord_dark')
aceThemes['Chaos'] = require('ace-builds/src-noconflict/theme-chaos')
aceThemes['GitHub'] = require('ace-builds/src-noconflict/theme-github')
aceThemes['One Dark'] = require('ace-builds/src-noconflict/theme-one_dark')
aceThemes['Chrome'] = require('ace-builds/src-noconflict/theme-chrome')
aceThemes['GitHub Light Default'] = require('ace-builds/src-noconflict/theme-github_light_default')
aceThemes['Pastel on Dark'] = require('ace-builds/src-noconflict/theme-pastel_on_dark')
aceThemes['Cloud9 Day'] = require('ace-builds/src-noconflict/theme-cloud9_day')
aceThemes['Gob'] = require('ace-builds/src-noconflict/theme-gob')
aceThemes['Solarized Dark'] = require('ace-builds/src-noconflict/theme-solarized_dark')
aceThemes['Cloud9 Night'] = require('ace-builds/src-noconflict/theme-cloud9_night')
aceThemes['Gruvbox Dark Hard'] = require('ace-builds/src-noconflict/theme-gruvbox_dark_hard')
aceThemes['Solarized Light'] = require('ace-builds/src-noconflict/theme-solarized_light')
aceThemes['Cloud9 Night Low Color'] = require('ace-builds/src-noconflict/theme-cloud9_night_low_color')
aceThemes['Gruvbox'] = require('ace-builds/src-noconflict/theme-gruvbox')
aceThemes['SqlServer'] = require('ace-builds/src-noconflict/theme-sqlserver')
aceThemes['Cloud Editor Dark'] = require('ace-builds/src-noconflict/theme-cloud_editor_dark')
aceThemes['Gruvbox Light Hard'] = require('ace-builds/src-noconflict/theme-gruvbox_light_hard')
aceThemes['Terminal'] = require('ace-builds/src-noconflict/theme-terminal')
aceThemes['Cloud Editor'] = require('ace-builds/src-noconflict/theme-cloud_editor')
aceThemes['Idle Fingers'] = require('ace-builds/src-noconflict/theme-idle_fingers')
aceThemes['Textmate'] = require('ace-builds/src-noconflict/theme-textmate')
aceThemes['Clouds'] = require('ace-builds/src-noconflict/theme-clouds')
aceThemes['Iplastic'] = require('ace-builds/src-noconflict/theme-iplastic')
aceThemes['Tomorrow'] = require('ace-builds/src-noconflict/theme-tomorrow')
aceThemes['Clouds Midnight'] = require('ace-builds/src-noconflict/theme-clouds_midnight')
aceThemes['Katzenmilch'] = require('ace-builds/src-noconflict/theme-katzenmilch')
aceThemes['Tomorrow Night Blue'] = require('ace-builds/src-noconflict/theme-tomorrow_night_blue')
aceThemes['Cobalt'] = require('ace-builds/src-noconflict/theme-cobalt')
aceThemes['KR Theme'] = require('ace-builds/src-noconflict/theme-kr_theme')
aceThemes['Tomorrow Night Bright'] = require('ace-builds/src-noconflict/theme-tomorrow_night_bright')
aceThemes['Crimson Editor'] = require('ace-builds/src-noconflict/theme-crimson_editor')
aceThemes['Kuroir'] = require('ace-builds/src-noconflict/theme-kuroir')
aceThemes['Tomorrow Night Eighties'] = require('ace-builds/src-noconflict/theme-tomorrow_night_eighties')
aceThemes['Dawn'] = require('ace-builds/src-noconflict/theme-dawn')
aceThemes['Merbivore'] = require('ace-builds/src-noconflict/theme-merbivore')
aceThemes['Tomorrow Night'] = require('ace-builds/src-noconflict/theme-tomorrow_night')
aceThemes['Dracula'] = require('ace-builds/src-noconflict/theme-dracula')
aceThemes['Merbivore Soft'] = require('ace-builds/src-noconflict/theme-merbivore_soft')
aceThemes['Twilight'] = require('ace-builds/src-noconflict/theme-twilight')
aceThemes['Dreamweaver'] = require('ace-builds/src-noconflict/theme-dreamweaver')
aceThemes['Mono Industrial'] = require('ace-builds/src-noconflict/theme-mono_industrial')
aceThemes['Vibrant Ink'] = require('ace-builds/src-noconflict/theme-vibrant_ink')
aceThemes['Eclipse'] = require('ace-builds/src-noconflict/theme-eclipse')
aceThemes['Monokai'] = require('ace-builds/src-noconflict/theme-monokai')
aceThemes['XCode'] = require('ace-builds/src-noconflict/theme-xcode')


module.exports = aceThemes